#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi


#- Remove trailing whitespace.
#-   http://qiita.com/k0kubun/items/8f6d7eded1d833187449

for diff in `git diff-index --check --cached $against -- |
  grep 'trailing whitespace' | sed 's/: trailing whitespace.//'`
do
  file=`echo "$diff" | sed 's/:[^:]*$//'`
  line=`echo "$diff" | sed 's/^[^:]*://'`

  sed -i -e "$line"'s/ *$//' "$file"
  git add "$file"
done


#- Fortran program: width limit of 132

for file in `git diff-index --cached --name-status HEAD | sed -e "/^D/d" | grep F90 | awk '{print $2}'`
do
  num_chara=`wc -L ${file} | awk '{print $1}'`
  if [ ${num_chara} -gt 132 ]; then
    echo "Error: number of characters in a line exceeds a limit (132). (${file})"
    exit 1
  fi
done

exit 0
